/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

/**
 *
 * @author Malintha Fernando
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LogoLable = new javax.swing.JLabel();
        logoutLable = new javax.swing.JLabel();
        profileIcone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        tileLabel = new javax.swing.JLabel();
        tileIcon = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        tileLabel1 = new javax.swing.JLabel();
        tileIcon1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        tileLabel2 = new javax.swing.JLabel();
        tileIcon2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        tileLabel3 = new javax.swing.JLabel();
        tileIcon3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        tileLabel4 = new javax.swing.JLabel();
        tileIcon4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        tileLabel6 = new javax.swing.JLabel();
        tileIcon6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        tileLabel7 = new javax.swing.JLabel();
        tileIcon7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        tileLabel8 = new javax.swing.JLabel();
        tileIcon8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setPreferredSize(new java.awt.Dimension(1370, 868));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLable.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LogoLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLable.setText("LOGO");
        Background.add(LogoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 100));

        logoutLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutLable.setForeground(new java.awt.Color(51, 51, 51));
        logoutLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLable.setText("Logout");
        Background.add(logoutLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 80, 50, -1));

        profileIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_male_50px.png"))); // NOI18N
        Background.add(profileIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-blur.jpg"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 140));

        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Background.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 490, 43));

        jPanel11.setBackground(new java.awt.Color(235, 236, 240));
        jPanel11.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel.setText("Patient");

        tileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_wheelchair_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon)
                .addGap(39, 39, 39))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        jPanel15.setBackground(new java.awt.Color(235, 236, 240));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setPreferredSize(new java.awt.Dimension(180, 200));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        tileLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel1.setText("Pharmacy");

        tileIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_hospital_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon1)
                .addGap(39, 39, 39))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        jPanel16.setBackground(new java.awt.Color(235, 236, 240));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel2.setText("Nursing");

        tileIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_nurse_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon2)
                .addGap(39, 39, 39))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        jPanel17.setBackground(new java.awt.Color(235, 236, 240));
        jPanel17.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel3.setText("Info");

        tileIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_info_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon3)
                .addGap(39, 39, 39))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, -1, -1));

        jPanel18.setBackground(new java.awt.Color(235, 236, 240));
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel4.setText("Cash Desk");

        tileIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_cash_100px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon4)
                .addGap(39, 39, 39))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jPanel20.setBackground(new java.awt.Color(235, 236, 240));
        jPanel20.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel6.setText("System");

        tileIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_system_task_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon6)
                .addGap(39, 39, 39))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon6)
                .addGap(27, 27, 27)
                .addComponent(tileLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Background.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, -1, -1));

        jPanel21.setBackground(new java.awt.Color(235, 236, 240));
        jPanel21.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel7.setText("Application");

        tileIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_application_window_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon7)
                .addGap(39, 39, 39))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jPanel22.setBackground(new java.awt.Color(235, 236, 240));
        jPanel22.setPreferredSize(new java.awt.Dimension(180, 200));

        tileLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tileLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tileLabel8.setText("Finance");

        tileIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bank_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tileLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tileIcon8)
                .addGap(39, 39, 39))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tileIcon8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(tileLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Background.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        
        pharmacySubMenu p = new pharmacySubMenu();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LogoLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logoutLable;
    private javax.swing.JLabel profileIcone;
    private javax.swing.JLabel tileIcon;
    private javax.swing.JLabel tileIcon1;
    private javax.swing.JLabel tileIcon2;
    private javax.swing.JLabel tileIcon3;
    private javax.swing.JLabel tileIcon4;
    private javax.swing.JLabel tileIcon6;
    private javax.swing.JLabel tileIcon7;
    private javax.swing.JLabel tileIcon8;
    private javax.swing.JLabel tileLabel;
    private javax.swing.JLabel tileLabel1;
    private javax.swing.JLabel tileLabel2;
    private javax.swing.JLabel tileLabel3;
    private javax.swing.JLabel tileLabel4;
    private javax.swing.JLabel tileLabel6;
    private javax.swing.JLabel tileLabel7;
    private javax.swing.JLabel tileLabel8;
    // End of variables declaration//GEN-END:variables
}
